version: 2

updates:
  # versions des actions utilisées dans les workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5

  # images utilisées dans les fichiers Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5

  # références des sous-modules back et front
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5