services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data_prod:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mariadb-admin ping -h 127.0.0.1 -u"$${MARIADB_USER}" -p"$${MARIADB_PASSWORD}" --silent'
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - database

  back:
    image: ghcr.io/inesenrq29/ressource-relationnelle-back:latest
    pull_policy: always
    container_name: rr-back
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SERVER_PORT: 8080
    networks:
      - application
      - database

  front:
    image: ghcr.io/inesenrq29/ressource-relationnelle-front:latest
    pull_policy: always
    container_name: rr-front
    restart: unless-stopped
    depends_on:
      - back
    ports:
      - "${FRONT_PORT:-80}:80"
    networks:
      - application

volumes:
  db_data_prod:

networks:
  application:
  database:
    internal: true